# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #Uses node 12
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - run: git remote set-url --push origin https://nilanshu96:$GITHUB_TOKEN@github.com/MDN-Breakout-Game.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # npm ci is a faster way to install modules on automated environments
      - name: install modules
        run: npm ci

      # Deploy the build folder to gh-pages
      - name: Deploy build to gh-pages
        run: npm run deploy
